server:
  port: 8888
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zmq.pojo
  mapper-locations: classpath*:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weixin-dev?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 28740000
      connection-test-query: SELECT 1
    username: root
    password: 123456
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 116.62.102.68:22122